# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'карта', 'verbose_name_plural': 'карты'},
        ),
    ]
