# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20170623_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='photomap',
            field=models.ImageField(blank=True, default='', upload_to='maps/photosmap', verbose_name='фотография карты'),
        ),
    ]
